# Copyright (C) 2026, KurobaM
# SPDX-License-Identifier: GPL-3.0-or-later

# to treat warning as error and perform 4 bytes align address:
#   python -W error non_psi3.py    

from __future__ import annotations
import hashlib
import os
import json
import sys

from common import load_json, SjisString


def auto_region_code(sjis: SjisString):
    out = [
        f'.org {hex(sjis.addr.value)}',
        f'.region {hex(sjis.addr.value + sjis.length)}-., 0x00',
        '.endregion',
        '',
        '.autoregion',
        f'txt_{hex(sjis.addr.value)[2:]}:',
        '.db ' + ', '.join(
            [f'0x{a:02x}' for a in sjis.trans.encode('sjis')]),
        '.align 4',
        '.endautoregion',
        '']
    for addr in sjis.p_addr:
        out.extend([
            f'.org {hex(addr.value)}',
            f'.dw org(txt_{hex(sjis.addr.value)[2:]})',
            ''])
    return '\n'.join(out)
        
     
def region_code(sjis: SjisString):
    out = [
        f'.org {hex(sjis.addr.value)}',
        f'.region {hex(sjis.addr.value + sjis.length)}-., 0x00',
        '.db ' + ', '.join(
            [f'0x{a:02x}' for a in sjis.trans.encode('sjis')]),
        '.endregion',
        '']
    return '\n'.join(out)

    
if __name__ == '__main__':
    path = os.path.abspath(os.path.join(
        os.path.dirname(__file__), '..', 'script/non_psi3', 'data.json'))
    out_path = os.path.abspath(os.path.join(
        os.path.dirname(__file__), '..', 'asm/non_psi3_script_text.asm'))
    config_path = os.path.abspath(os.path.join(
        os.path.dirname(__file__), 'non_psi3_config.json'))
    config = dict()
    with open(path, 'rb') as f:
        raw = f.read()
    config[path] = hashlib.sha256(raw).hexdigest()

    if not os.path.isfile(config_path):
        with open(config_path, 'w') as f:
            json.dump(config, f)
    else:
        with open(config_path, 'r') as f:
            data = json.load(f)
        if data[path] == config[path]:
            sys.exit()
        with open(config_path, 'w') as f:
            json.dump(config, f)      
        
    if os.path.isfile(path):
        data = load_json(path)
    else:
        sys.exit()
    out = ['; This file content is autogenerated']
    data.pop('__version__')
    for k in data:
        sjis = data[k]
        if len(sjis.trans.encode('sjis')) > sjis.length:
            out.append(auto_region_code(sjis))
        else:
            if sjis.trans == '':
                continue
            out.append(region_code(sjis))
    with open(out_path, 'w') as f:
        f.write('\n'.join(out))
    print(f'Write non-psi3 script text to {out_path}')    
